version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
  
  mongo-seed:
    build: ..
    image: fvilers/mongo-seed
    # depends_on:
    #   - mongo
    volumes:
      - ./data:/data
    command:
      "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/people.json --jsonArray"
